name: datn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logger:
    path: logger

  path_provider_android: ^2.2.15
  path_provider: ^2.1.5

  shared_preferences: ^2.3.3
  shared_preferences_android: ^2.4.0
  shared_preferences_foundation: ^2.5.4

  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  collection: ^1.18.0
  fl_chart: ^0.69.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^17.2.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  flutter_timezone: ^3.0.1
  fluttertoast: ^8.2.8
  get: ^4.6.6
  hive: ^2.2.3
  intl: ^0.19.0

  lottie: ^3.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  get_it: ^8.0.3
  csv: ^6.0.0
  share_plus: ^10.1.3
  flutter_inappwebview: ^6.1.5
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/lottie/
    - assets/png/
    - assets/svg/


  fonts:
    - family: Poppins
      fonts:
        - asset: font/poppins_light_300.ttf
          weight: 300
        - asset: font/poppins_regular_400.ttf
          weight: 400
        - asset: font/poppins_medium_500.ttf
          weight: 500
        - asset: font/poppins_semi_bold_600.ttf
          weight: 600
        - asset: font/poppins_bold_700.ttf
          weight: 700
